
export enum ApiIntentResponseTypeEnum {
  QUERY_OK = 'QUERY_OK',
  HTTP_OK = 'HTTP_OK',
  PRECONDITIONS_MISSING = 'PRECONDITIONS_MISSING',
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  TOUR_NOT_FOUND = 'TOUR_NOT_FOUND',
  OBJECT_IN_PORTAL_NOT_FOUND = 'OBJECT_IN_PORTAL_NOT_FOUND',
  ITEM_ALREADY_LINKED = 'ITEM_ALREADY_LINKED',
  ITEM_UNLINKING_PENDING = 'ITEM_UNLINKING_PENDING',
  ITEM_UNLINKED = 'ITEM_UNLINKED',
  PORTAL_CREATED = 'PORTAL_CREATED',
  ITEM_DELETED = 'ITEM_DELETED',
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  RESOURCE_RESTRICTED = 'RESOURCE_RESTRICTED'
}

export type ApiIntentResponseType = keyof typeof ApiIntentResponseTypeEnum;
